### ISSUE TITLE
Fix the title of the app

### ISSUE THREAD

**Issue by Ktn-mariam** [Ktn-mariam/ecommerce_assgnmt#3]
Currently, it shows 'React App' in the title of the page.
Fix that to 'E-commerce App' with the loremipsum logo.

**Comment by suman2mandal** [comment]
Hi, I'm interested in contributing to this project and would like to request access to the repository. I have fixed this issue in the code and would like to submit my changes. Could you please grant me access? Thank you!

**Comment by Ktn-mariam** [comment]
Thank you, @suman2mandal! Feel free to fork this repository and submit a pull request. I would be happy to merge the changes you have made.
